version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          rules: ${base-path}/tools/rules.go
        underef:
          skipRecvDeref: false
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    nakedret:
      max-func-lines: 0
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - forbidigo
        - tracecheck
        - gomnd
        - gochecknoinits
        - makezero
    revive:
      severity: error
      rules:
        - name: atomic
        - name: line-length-limit
          arguments:
            - 200
          exclude:
            - pkg/bcb/generate.go
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
            - fmt.Fprint
            - fmt.Fprintf
            - fmt.Fprintln
            - os.Stderr.Sync
            - sb.WriteString
            - buf.WriteString
            - hasher.Write
            - os.Setenv
            - os.RemoveAll
        - name: var-naming
          arguments:
            - - ID
              - URL
              - HTTP
              - API
            - []
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
        source: (TODO)
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
