name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Run linters
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.4
        args: --timeout=3m
  go-test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      if: success()
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: go tests
      run: go test -v -covermode=count -json ./... > test.json
    - name: annotate go tests
      if: always()
      uses: guyarb/golang-test-annotations@v0.6.0
      with:
        test-results: test.json
  buf-lint-and-breaking-change-detection:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: bufbuild/buf-setup-action@v1
      with:
        version: '1.50.0'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Lint
      uses: bufbuild/buf-lint-action@v1
    - name: Breaking change detection against `main`
      uses: bufbuild/buf-breaking-action@v1
      with:
        against: 'https://github.com/conductorone/baton.git#branch=main'
